# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: NH - X-ray 자동화 장비 전문 제조업체
email: info@nhco.kr
description: >-
  엔에이치는 X-ray, 광학비전 검사 장비 및 자동화 솔루션을 제조하는 전문업체입니다. 
  로봇 기술과 결합한 혁신적인 검사·측정·분석·가공 장비를 공급합니다.
baseurl: "" # GitHub Pages에서 자동으로 설정됨
url: "https://nhco.kr" # 실제 도메인
# twitter_username: jekyllrb
github_username: nhco25

# SEO 설정
author:
  name: NH 주식회사
  email: info@nhco.kr
  
# 소셜 미디어 및 검색엔진 최적화
social:
  name: NH 주식회사
  links:
    - https://github.com/nhco25

# 언어 설정
lang: ko-KR

# 회사 정보 (구조화된 데이터용)
company:
  name: NH 주식회사
  address: 
    street: ""
    city: ""
    state: ""
    zip: ""
    country: "대한민국"
  phone: ""
  email: info@nhco.kr
  founded: ""
  industry: "X-ray 자동화 장비 제조"

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .well-known/

# 컬렉션
collections:
  products:
    output: true
    permalink: /products/:title/

# 제품 태그 설정
product_tags:
  - name: X-ray 검사 장비
    slug: xray
  - name: 자동화 솔루션
    slug: automation
  - name: 맞춤형 장비
    slug: custom
